#!/bin/sh

### SEPARATORS ###
# left separator
SEP1='['
# right separator
SEP2=']'

### SLEEP TIME ###
SLP=1

### TIME MODULE ###
dwm_time() {
   echo "$SEP1 $(date | awk '{ print $5 }') $SEP2"
}

### BATTERY MODULE ###
dwm_battery() {
   STATUS=$(cat /sys/class/power_supply/BAT0/status)
   CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)

   if [ $STATUS = "Charging" ];
   then
      STATUS="c"
   elif [ $STATUS = "Discharging" ];
   then
      STATUS="d"
   fi

   echo "$SEP1 BAT $CHARGE% ($STATUS) $SEP2"
}

### WLAN MODULE ###
dwm_wlan() {
   STATUS="$(nmcli | head -n 1 | awk '{ print $2 }')"
   if [ $STATUS = "connected" ];
   then
      STATUS="$(nmcli | head -n 1 | awk '{ print $4 }')"
   fi

   echo "$SEP1 WLAN $STATUS $SEP2"
}

### BRIGHTNESS MODULE ###
dwm_brightness() {
   BRIGHTNESS_MAX=$(cat /sys/class/backlight/intel_backlight/max_brightness)
   BRIGHTNESS_CURRENT=$(cat /sys/class/backlight/intel_backlight/brightness)
   BRIGHTNESS_PERCENTAGE=$(($BRIGHTNESS_CURRENT * 100 / $BRIGHTNESS_MAX))

   echo "$SEP1 BR $BRIGHTNESS_PERCENTAGE% $SEP2"
}

### CPU MODULE ###
dwm_cpu() {
   CPU_TEMPERATURE=$(sensors | head -n 3 | tail -n 1 | awk '{ print $4 }')
   CPU_PERCENTAGE=$(top -bn 1 | head -n 3 | tail -n 1 | awk '{ print 100-$8}')
   CPU_PERCENTAGE=${CPU_PERCENTAGE%.*}

   echo "$SEP1 CPU $CPU_PERCENTAGE% $CPU_TEMPERATURE $SEP2"
}

### MEMORY MODULE ###
dwm_memory() {
   RAM_MAX=$(top -bn 1 | grep "MiB Mem" | awk '{ print $4 }')
   RAM_MAX=${RAM_MAX%.*}
   RAM_CURRENT=$(top -bn 1 | grep "MiB Mem" | awk '{ print $8 }')
   RAM_CURRENT=${RAM_CURRENT%.*}
   RAM_PERCENTAGE=$(($RAM_CURRENT * 100 / $RAM_MAX))

   echo "$SEP1 MEM $RAM_PERCENTAGE% $SEP2"
}

### FAN MODULE ###
dwm_fan() {
   FAN_RPM=$(sensors | tail -n 2 | head -n 1 | awk '{ print $2 }')

   echo "$SEP1 FAN $FAN_RPM rpm $SEP2"
}

### VOLUME MODULE ###
dwm_volume() {
   VOLUME=$(pactl list sinks | grep '^[[:space:]]Volume:' |     head -n $(( $SINK + 1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,')

   echo "$SEP1 VOL $VOLUME% $SEP2"
}

### MAIN MODULE ###
while true;
do
   xsetroot -name " $(dwm_memory)$(dwm_cpu)$(dwm_wlan)$(dwm_brightness)$(dwm_battery)$(dwm_volume)$(dwm_time)"
   sleep $SLP
done &
