#!/bin/sh

### SEPARATORS ###
# left separator
SEP1='['
# right separator
SEP2=']'

### SLEEP TIME ###
SLP=1

### TIME MODULE ###
dwm_time() {
   echo "$SEP1 $(date | awk '{ print $5 }') $SEP2"
}

### BATTERY MODULE ###
dwm_battery() {
   STATUS=$(cat /sys/class/power_supply/BAT0/status)
   CHARGE=$(cat /sys/class/power_supply/BAT0/capacity)

   if [ $STATUS = "Charging" ];
   then
      STATUS="c"
   elif [ $STATUS = "Discharging" ];
   then
      STATUS="d"
   fi

   echo "$SEP1 BAT $CHARGE% ($STATUS) $SEP2"
}

### WLAN MODULE ###
dwm_wlan() {
   STATUS="$(nmcli | head -n 1 | awk '{ print $2 }')"
   if [ $STATUS = "connected" ];
   then
      STATUS="$(nmcli | head -n 1 | awk '{ print $4 }')"
   fi

   echo "$SEP1 WLAN $STATUS $SEP2"
}

### BRIGHTNESS MODULE ###
dwm_brightness() {
   BRIGHTNESS_MAX=$(cat /sys/class/backlight/intel_backlight/max_brightness)
   BRIGHTNESS_CURRENT=$(cat /sys/class/backlight/intel_backlight/brightness)
   BRIGHTNESS_PERCENTAGE=$(($BRIGHTNESS_CURRENT * 100 / $BRIGHTNESS_MAX))

   echo "$SEP1 BR $BRIGHTNESS_PERCENTAGE% $SEP2"
}

### MEMORY MODULE ###
dwm_memory() {
   RAM_MAX=$(free -m | head -n 2 | tail -n 1 | awk '{ print $2 }')
   RAM_MAX=${RAM_MAX%.*}
   RAM_USED=$(free -m | head -n 2 | tail -n 1 | awk '{ print $3 }')
   RAM_USED=${RAM_USED%.*}
   RAM_PERCENTAGE=$(($RAM_USED * 100 / $RAM_MAX))

   echo "$SEP1 MEM $RAM_PERCENTAGE% $SEP2"
}

### FAN MODULE ###
dwm_fan() {
   FAN_RPM=$(sensors | tail -n 2 | head -n 1 | awk '{ print $2 }')

   echo "$SEP1 FAN $FAN_RPM rpm $SEP2"
}

### VOLUME MODULE ###
dwm_volume() {
   MUTE=$(pactl list sinks | grep Mute | awk '{ print $2 }')
   VOLUME=$(pactl list sinks | grep Volume | head -n 1 | awk '{ print $5 }')

   TAG=""
   if [ $MUTE = "yes" ];
   then
     TAG="mute"
   else
     TAG=$VOLUME
   fi

   echo "$SEP1 VOL $TAG $SEP2"
}

### CPU MODULE ###
dwm_cpu() {
  CPU=$(sensors | head -n 3 | tail -n 1 | awk '{ print $4 }')

  echo "$SEP1 CPU $CPU $SEP2"
}

### MAIN LOOP ###
while true;
do
  xsetroot -name " $(dwm_memory)$(dwm_cpu)$(dwm_wlan)$(dwm_brightness)$(dwm_battery)$(dwm_volume)$(dwm_time)"
  sleep $SLP
done &
